[schedule]
run_seconds = 5 # Run interval in seconds
target_listings_count = 100 # Number of listings to aim for

[search] # New section for search parameters
search_keyword = "smith 27"
search_type_category = "Revolvers"

[email]
# --- Email Configuration ---
# Note: Using App Passwords is recommended for services like Gmail.

# Example for Gmail:
# smtp_server = "smtp.gmail.com"
# smtp_port = 587 # Use 465 for SSL

# Example for generic SMTP:
smtp_server = "smtp.mailersend.net"
smtp_port = 587 # Common port for TLS
use_ssl = false # Set to true if using port 465 typically

sender_email = "MS_LNqnhE@test-xkjn41m20e04z781.mlsender.net"
sender_password = "mssp.6k5ozcb.0r83ql3ok2plzw1j.Wq6csPR" # Use App Password if possible!
recipient_emails = ["greendude720@gmail.com", "garrettlshuck@gmail.com"] # Add more emails inside the brackets, separated by commas
